replicaCount: 1

replica:
  autoscaling: 
    enabled: false
image:
  repository: redis
  tag: 7.2.3
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

# volume:
#   size: 1Gi
#   storageClassName: standard
#   hostPath: data.rdb

service:
  type: ClusterIP
  port: 6379

redis:
  port: 6379
  # Define a password to use on the redis server or 20 alphanumeric character one will be randomly generated
  # password: ""
  persistence:
    enabled: true
    storageClassName: ""
  saves:
    - seconds: 900
      threshold: 10
    - seconds: 30
      threshold: 3