apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.goApp.tlsSecretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "tls.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "tls.key" | b64enc | quote }}